build-sys: require spice-protocol 0.12.4
This is mostly needed form client side optimizations on streaming
mode. The following change introduced dependency of latest
spice-protocol:

 | commit 424397546463698c2912b15449ef5e94f2c39c12
 | Author: Snir Sheriber <ssheribe@redhat.com>
 | Date:   Thu Mar 8 15:57:31 2018 +0200
 |
 | Gstreamer: Use GstVideoOverlay if possible

The spice-protocol commit for reference:

 | commit 4250216bafd37905afe0e9ad8cb9beb4a0c89254
 | Author: Frediano Ziglio <fziglio@redhat.com>
 | Date:   Tue Nov 7 10:45:20 2017 +0000
 |
 | Allow to specify a surface will be streamed
 |
 | This flag will allow the client to perform some optimisations
 | on output and buffering processing.
 | Old clients will ignore this additional flag.

Note that without bumping the requirement, the code would fail to
build with:

 | channel-display.c:1809:50: error: ‘SPICE_SURFACE_FLAGS_STREAMING_MODE’
 | undeclared (first use in this function); did you mean ‘SPICE_DISPLAY_STREAMING_MODE’?
 |      surface->streaming_mode = !!(create->flags & SPICE_SURFACE_FLAGS_STREAMING_MODE);
 |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Victor Toso <victortoso@redhat.com>
Acked-by: Frediano Ziglio <fziglio@redhat.com>