Fix printf format string warning
When doing a mingw32 build, I hit the following warning (which became an
error because of -Werror):

channel-display.c: In function 'destroy_stream':
channel-display.c:1546:9: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'uint64_t' [-Werror=format=]
         CHANNEL_DEBUG(channel, "%s: drops total duration %lu ==>", __FUNCTION__, drops_duration_total);
         ^