mingw64: Fix gssize printf-format warnings
When building with mingw64, several warnings about using the wrong format
specifier for gssize/gsize occur similar to:

win-usb-dev.c: In function 'g_udev_client_list_devices':
win-usb-dev.c:145:21: error: format '%i' expects argument of type 'int', but argument 7 has type 'gssize' [-Werror=format=]
                     name, errstr, rc);

This commit makes use of the G_GSIZE_FORMAT/G_GSSIZE_FORMAT macros provided
by glib to silence these warnings.

I've checked that this does not introduce new warnings on linux and mingw32
builds.