usb-device-manager: mingw: win driver install callback: add missing ifdef
This fixes the following compilation error message (without USE_USBREDIR):

usb-device-manager.c:183:13: error: 'spice_usb_device_manager_drv_install_cb' declared 'static' but never defined [-Werror=unused-function]