Update spice-common
This is an update to fix build issues with spice-protocol.git.
generated_server_demarshallers.c: In function
‘parse_msgc_display_gl_draw_done’:
generated_server_demarshallers.c:767:23: error:
‘SpiceMsgcDisplayGlDrawDone’ undeclared (first use in this function)
     mem_size = sizeof(SpiceMsgcDisplayGlDrawDone);
...

Also needed for upcoming gl-scanout messages.

Signed-off-by: Marc-André Lureau <marcandre.lureau@gmail.com>
Acked-by: Frediano Ziglio <fziglio@redhat.com>