vncdisplaykeymap: Include missing headers
Causing build failures on win32
 .libs/vncdisplaykeymap.o: In function `vnc_display_keymap_gdk2xtkbd_table':
  /builddir/build/BUILD/spice-gtk-0.33.19-efbfd/build_win32/src/../../src/vncdisplaykeymap.c:198: undefined reference to `GDK_IS_WIN32_WINDOW'
 collect2: error: ld returned 1 exit status

Regression from 9ff67a108bb76e50a2c85a5054e6521088df1800
Acked-by: Frediano Ziglio <fziglio@redhat.com>