Fix build without egl
spice_display_widget_gl_scanout is defined only when building with egl
 ./.libs/libspice-client-gtk-3.0.so: undefined reference to `spice_display_widget_gl_scanout'

Fixes 977db3bb3da94def4c0e1d4087037303d250e158