unused variable 'self' if !USE_USB
CC     spice-widget-enums.lo
desktop-integration.c: In function 'spice_desktop_integration_dispose':
desktop-integration.c:175:30: error: unused variable 'self'
[-Werror=unused-variable]