Use local GError in spice_convert_newlines()
spice_convert_newlines() declares a local 'err' GError but never uses it as
the function directly uses the 'error' variable passed as an argument.
Use 'err' throughout the function instead of the 'error' argument as this
looks like what was intended.
This fixes this coverity warning:

Error: DEADCODE (CWE-561): [#def144]
spice-gtk-0.22.9-fb3d/spice-gtk3-0.22.9/gtk/spice-util.c:318: assignment: Assigning: "err" = "NULL".
spice-gtk-0.22.9-fb3d/spice-gtk3-0.22.9/gtk/spice-util.c:364: null: At condition "err", the value of "err" must be NULL.
spice-gtk-0.22.9-fb3d/spice-gtk3-0.22.9/gtk/spice-util.c:364: dead_error_condition: The condition "err" cannot be true.
spice-gtk-0.22.9-fb3d/spice-gtk3-0.22.9/gtk/spice-util.c:365: dead_error_begin: Execution cannot reach this statement "g_propagate_error(error, err);".