spicy: Fix compilation breaking due to a compiler warning
This fixes:
spicy.c:1711:10: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]

Signed-off-by: Hans de Goede <hdegoede@redhat.com>